- application/configs/application.ini
- application/configs/config.ini.template
- composer.json
- library/Application/Util/DocumentAdapter.php
- library/Application/View/Helper/Abstract.php
- library/Application/View/Helper/Document/HelperAbstract.php
- library/Application/View/Helper/DocumentAbstract.php
- library/Application/View/Helper/DocumentTitle.php
- modules/solrsearch/views/scripts/index/results.phtml
- public/layouts/opus4/css/opus.css
- tests/library/Application/Util/DocumentAdapterTest.php
- tests/library/Application/View/Helper/DocumentTitleTest.php
> OPUSVIER-3496 - Anzeige von Suchergebnissen in Sprache der Oberfläche

- library/Application/View/Helper/FileLink.php
- public/layouts/opus4/css/admin.css
> OPUSVIER-3710 Rendering of long file names in file manager.

- modules/citationExport/models/Helper.php
- modules/citationExport/views/scripts/index/bibtex.xslt
- modules/citationExport/views/scripts/index/bibtex_article.xslt
- modules/citationExport/views/scripts/index/bibtex_book.xslt
- modules/citationExport/views/scripts/index/bibtex_bookpart.xslt
- modules/citationExport/views/scripts/index/bibtex_conferenceobject.xslt
- modules/citationExport/views/scripts/index/bibtex_doctoralthesis.xslt
- modules/citationExport/views/scripts/index/bibtex_masterthesis.xslt
- modules/citationExport/views/scripts/index/bibtex_preprint.xslt
- modules/citationExport/views/scripts/index/bibtex_report.xslt
- modules/citationExport/views/scripts/index/ris.xslt
Removed usage of Opus_Model_Filter and simplified XSLT files.
> OPUSVIER-1292 - Kleiner Umbau bei BibTeX und RIS Export XSLT.

- library/Application/Controller/Action/Helper/Breadcrumbs.php
- library/Application/View/Helper/FormatDate.php
- modules/admin/views/scripts/actionbox.phtml
- modules/frontdoor/views/scripts/actionbox.phtml
- tests/library/Application/View/Helper/FormatDateTest.php
> OPUSVIER-3739 - Show time for published and modified in administration.

- library/Application/Controller/Action/Helper/Abstract.php
- library/Application/Controller/Action/Helper/Breadcrumbs.php
- modules/oai/views/scripts/index/prefixes/oai_dc.xslt
- tests/library/Application/Controller/Action/Helper/BreadcrumbsTest.php
- tests/modules/oai/controllers/IndexControllerTest.php
Der Branch enthält auch noch einen anderen Bugfix in den Tests.
> OPUSVIER-3418 - OpenAIRE Anpassungen

- application/configs/application.ini
- library/Application/Form/Validate/Identifier.php
- tests/library/Application/Form/Validate/IdentifierTest.php
change the delegation of validator for identifier.
Validators are now set in the application.ini
Add issn-validation
> OPUSVIER-2386

- tests/modules/admin/controllers/DnbinstituteControllerTest.php
- tests/modules/admin/controllers/EnrichmentkeyControllerTest.php
- tests/modules/admin/controllers/IprangeControllerTest.php
- tests/modules/admin/controllers/LanguageControllerTest.php
- tests/modules/admin/controllers/LicenceControllerTest.php
- tests/modules/admin/controllers/PersonControllerTest.php
- tests/modules/admin/controllers/SeriesControllerTest.php
- tests/support/CrudControllerTestCase.php
> OPUSVIER-3925

- modules/publish/controllers/FormController.php
- modules/publish/language/errors.tmx
- modules/publish/views/scripts/index/index.phtml
- public/layouts/opus4/js/filetypes.js
add filesize error-message in publish-upload
> OPUSVIER-3931

- library/Application/Form/Validate/Filename.php
- tests/library/Application/Form/Validate/FilenameTest.php
> Opusvier 3908

- library/Application/Controller/Action.php
- library/Application/Form/Element/EnrichmentKey.php
- modules/admin/controllers/AutocompleteController.php
- modules/admin/controllers/DocumentController.php
- modules/admin/controllers/EnrichmentkeyController.php
- modules/admin/forms/AbstractDocumentSubForm.php
- modules/admin/forms/Document/Enrichment.php
- modules/admin/forms/Document/MultiEnrichmentSubForm.php
- modules/admin/forms/Document/MultiSubForm.php
- modules/admin/forms/EnrichmentKey.php
- modules/admin/language/enrichmentkey.tmx
- modules/admin/language/validation.tmx
- modules/admin/views/scripts/enrichmentkey/modeltable.phtml
- public/layouts/opus4/css/admin.css
- public/layouts/opus4/js/theme.js
- tests/library/Application/Form/Element/EnrichmentKeyTest.php
- tests/modules/admin/controllers/AutocompleteControllerTest.php
- tests/modules/admin/controllers/EnrichmentkeyControllerTest.php
- tests/modules/admin/forms/Document/EnrichmentTest.php
- tests/modules/admin/forms/Document/MultiEnrichmentSubFormTest.php
- tests/modules/admin/forms/Document/MultiSubFormTest.php
- tests/modules/admin/forms/EnrichmentKeyTest.php
Hier kommen alle Änderungen in der OPUS4-Webapplikation, um Enrichment Types zu unterstützen.
> Application changes to support enrichment types in OPUS 4.6.4

- library/Application/View/Helper/Translate.php
Make sure first parameter is never interpreted as Locale and arrays are
handled properly.
> OPUSVIER-2546 Fixed handling of translation parameters.

- modules/export/language/export.tmx
Änderungen nach Vorgabe von Signe (in https://github.com/OPUS4/userdoc/pull/77)
> OPUSVIER-3978: Nachbesserung in Übersetzungen

- modules/admin/forms/Document/Collections.php
- tests/modules/admin/forms/Document/CollectionsTest.php
> OPUSVIER-4020 Fixed collection role names with dashes handling.

- bin/install-php-packages.sh
entsprechende Änderung in der Doku in PR https://github.com/OPUS4/userdoc/pull/78
> added missing dependency php-zip (required by module sword)

- tests/modules/admin/controllers/FilemanagerControllerTest.php
- tests/modules/admin/controllers/PersonControllerTest.php
- tests/modules/admin/models/DoiReportTest.php
- tests/modules/frontdoor/controllers/IndexControllerTest.php
- tests/modules/publish/controllers/DepositControllerTest.php
- tests/modules/publish/models/DepositTest.php
- tests/support/ControllerTestCase.php
Mal schauen, was der Travis Build für Probleme beim Testdokument-Cleanup findet, die uns bislang unterschlagen wurden.
> OPUSVIER-4124

- library/Application/View/Helper/ActionCssClass.php
- library/Application/View/Helper/AdminCssClass.php
- public/layouts/default/common.phtml
- public/layouts/opus4/common.phtml
- tests/library/Application/View/Helper/ActionCssClassTest.php
- tests/library/Application/View/Helper/AdminCssClassTest.php
Remove difficult to read PHP code from PHTML file.
> OPUSVIER-4129 Use view helper to render CSS classes.

- tests/library/Application/TranslateTest.php
- tests/library/Application/Util/NotificationTest.php
- tests/library/Application/Util/PublicationNotificationTest.php
- tests/library/Application/View/Helper/CustomFileSortingEnabledTest.php
- tests/library/Application/View/Helper/DocumentTitleTest.php
- tests/library/Application/View/Helper/IsDisplayFieldTest.php
- tests/library/Application/View/Helper/OptionEnabledTest.php
- tests/library/Application/ZendBasicsTest.php
- tests/modules/account/controllers/IndexControllerTest.php
- tests/modules/admin/controllers/IndexmaintenanceControllerTest.php
- tests/modules/admin/controllers/JobControllerTest.php
- tests/modules/admin/controllers/WorkflowControllerTest.php
- tests/modules/admin/models/IndexMaintenanceTest.php
- tests/modules/export/BibtexExportTest.php
- tests/modules/export/Marc21ExportTest.php
- tests/modules/export/controllers/IndexControllerTest.php
- tests/modules/export/models/XmlExportTest.php
- tests/modules/frontdoor/controllers/IndexControllerTest.php
- tests/modules/home/controllers/IndexControllerTest.php
- tests/modules/oai/controllers/ContainerControllerTest.php
- tests/modules/oai/controllers/IndexControllerTest.php
- tests/modules/oai/models/ContainerTest.php
- tests/modules/publish/controllers/FormControllerTest.php
- tests/modules/publish/controllers/IndexControllerTest.php
- tests/modules/publish/forms/PublishingFirstTest.php
- tests/modules/solrsearch/controllers/IndexControllerTest.php
- tests/modules/solrsearch/models/SeriesUtilTest.php
- tests/support/ControllerTestCase.php
- tests/tests.ini
Dieser PR umfasst Änderungen, die im Rahmen des Code Reviews gewünscht wurden.
> Improvements of OPUSVIER-4112

- modules/publish/language/field_hints.tmx
Exchange of the new suggested help text for the DDC classification
> OPUSVIER-4142 Update of DDC help text and link.

- library/Application/Controller/Action/Helper/DocumentTypes.php
- library/Application/Import/Importer.php
- modules/admin/controllers/WorkflowController.php
- tests/library/Application/Controller/Action/Helper/DocumentTypesTest.php
- tests/modules/oai/controllers/IndexControllerTest.php
OPUSVIER-4075 Fixed bug in the method _sendNotification
> OPUSVIER-4075 Bugfix sending notifications

- tests/rebuilding_database.sh
> OPUSVIER-4092

- modules/frontdoor/controllers/IndexController.php
- modules/frontdoor/models/HtmlMetaTags.php
- tests/modules/frontdoor/models/HtmlMetaTagsTest.php
Also adding lang attribute to abstracts and titles.
> OPUSVIER-4188 Add dcterms.abstract to Frontdoor meta tags.

- modules/oai/views/scripts/index/oai-pmh.xslt
- modules/oai/views/scripts/index/prefixes/marc21.xslt
- modules/oai/views/scripts/index/prefixes/oai_dc.xslt
Correcting MARC Leader 07 and Relator Code in 700 $4
> Updating OAI MARCXML export

- modules/admin/forms/EnrichmentKey.php
- modules/admin/language/enrichmentkey.tmx
- tests/modules/admin/controllers/EnrichmentkeyControllerTest.php
- tests/modules/admin/forms/EnrichmentKeyTest.php
required application changes for OPUSVIER-4196
> OPUSVIER-4196

- modules/default/language/fieldnames.tmx
- modules/export/language/export.tmx
- modules/export/models/DataciteExport.php
- modules/export/views/scripts/index/datacite.phtml
- tests/modules/export/DataCiteExportTest.php
Diesen PR bitte erst *nach* dem Merge von Framework-PR https://github.com/OPUS4/framework/pull/92 durchführen.
> OPUSVIER-4054

- modules/admin/forms/EnrichmentKey.php
- tests/modules/admin/controllers/EnrichmentkeyControllerTest.php
- tests/modules/admin/forms/EnrichmentKeyTest.php
kontextsensitive Bestimmung der Pflichtfeld-Eigenschaft für Formularfeld EK-Type
> OPUSVIER-4139

- Jenkinsfile
- composer.json
- tests/library/Application/View/Helper/LanguageWebFormTest.php
Ändere cover in LanguageWebFormTest
Hinzufügen von Test and Analyse-Funktionen zu Composer
Ändern der Long-Build Bedingungen
Das Coverage wird jetzt hier nur einmal die Woche (beginnend Freitag Abend 21:00) für den Master und den Entwicklungsbranch durchgeführt. Grund dafür ist die lange Dauer der Tests mit Coverage.
> OPUSVIER-3772 CI-System

- library/Application/Update/ImportHelpFiles.php
- modules/home/models/HelpFiles.php
- tests/library/Application/Update/ImportHelpFilesTest.php
- tests/library/Application/Util/FileTest.php
- tests/library/Application/View/Helper/FileAccessAllowedTest.php
- tests/library/Application/View/Helper/FulltextLogoTest.php
- tests/modules/ControllerTestCaseTest.php
- tests/modules/admin/controllers/DocumentControllerTest.php
- tests/modules/admin/controllers/FilemanagerControllerTest.php
- tests/modules/frontdoor/controllers/DeliverControllerTest.php
- tests/modules/frontdoor/controllers/IndexControllerTest.php
- tests/modules/frontdoor/models/FileTest.php
- tests/modules/frontdoor/models/HtmlMetaTagsTest.php
- tests/modules/oai/controllers/IndexControllerTest.php
- tests/modules/oai/models/ContainerTest.php
- tests/modules/oai/models/DocumentListTest.php
- tests/modules/oai/models/XmlFactoryTest.php
- tests/support/ControllerTestCase.php
Use help.ini to determine the correct content files during 4.7 update.
> OPUSVIER-4249 Using help.ini during 4.7 update

- modules/admin/forms/EnrichmentKey.php
- modules/admin/models/EnrichmentKeys.php
- tests/modules/admin/forms/EnrichmentKeyTest.php
> OPUSVIER-4161 Fixed warning. Test cleanup.

- .github/workflows/php.yml
- public/layouts/default/common.phtml
- public/layouts/opus4/debug.phtml
> Issue #373

- RELEASE_NOTES.md
- Hinweis zur Abhängigkeit auf **Pandoc** eingefügt
- kleinere Verbesserungen in Formulierungen
> OPUSVIER-4065: minor improvements in release notes

- modules/setup/forms/FaqItem.php
- tests/modules/setup/forms/FaqItemTest.php
This is a quick hack. The system should be generalized. Cleanup is still necessary for translation system.
> OPUSVIER-4560 Special handling for FAQ imprint, contact

- tests/modules/admin/forms/Document/SubjectTypeTest.php
- tests/modules/export/DataCiteExportTest.php
> Fix language dependent unit tests

- application/configs/application.ini
- modules/export/views/scripts/publist/default.xslt
- modules/frontdoor/views/scripts/index/templates/metadata.xslt
- tests/modules/export/controllers/IndexControllerTest.php
- tests/modules/frontdoor/controllers/IndexControllerTest.php
> #485 Pubmed base url configurable

- Vagrantfile
- application/configs/navigationModules.xml
- library/Application/Console/App.php
- modules/admin/controllers/ImportController.php
- modules/admin/forms/Import.php
- modules/admin/language/import.tmx
- modules/admin/views/scripts/import/bibtex.phtml
> BibTeX Konfiguration vereinfachen

- application/configs/application.ini
- application/configs/covers/README.md
- bin/prepare-workspace.sh
- build.xml
- composer.json
- library/Application/Configuration.php
- modules/frontdoor/controllers/DeliverController.php
> PDF covers: Application-side code to add a PDF cover page in front of a downloaded PDF file

- tests/library/Application/Controller/Action/Helper/DocumentTypesTest.php
- tests/library/Application/Controller/ActionCRUDTest.php
- tests/library/Application/Controller/MessageTemplatesTest.php
- tests/library/Application/Controller/ModuleAccessTest.phtml
- tests/library/Application/Form/ConfirmationTest.php
- tests/library/Application/Form/Element/FileLinkTest.php
- tests/library/Application/Form/Element/ThemeTest.php
- tests/library/Application/Form/Model/AbstractTest.php
- tests/library/Application/Form/Model/TableTest.php
- tests/library/Application/Form/TableHeaderTest.php
- tests/library/Application/Form/Validate/IdentifierTest.php
- tests/library/Application/Form/Validate/MultiSubForm/RepeatedValuesTest.php
- tests/library/Application/Util/FileTest.php
- tests/modules/ControllerTestCaseTest.php
- tests/modules/admin/forms/Document/InstituteTest.php
- tests/modules/admin/forms/Document/MultiSubFormTest.php
- tests/modules/admin/forms/FileTest.php
- tests/modules/admin/models/CollectionRoleTest.php
- tests/modules/admin/models/FileImportTest.php
- tests/modules/citationExport/model/HelperTest.php
- tests/modules/oai/models/ContainerTest.php
- tests/modules/oai/models/ErrorTest.php
- tests/modules/publish/controllers/DepositControllerTest.php
- tests/modules/publish/forms/PublishingSecondTest.php
- tests/modules/publish/models/DepositTest.php
- tests/modules/publish/models/DocumenttypeParserTest.php
> Replaces deprecated @expectedException(Message) annotations

- library/Application/Controller/ActionCRUD.php
- tests/modules/admin/controllers/SeriesControllerTest.php
Temporary fix until translation keys are changed to be class independent.
> #555 Fix translation of model classes in admin pages

- library/Application/Console/App.php
> Integration des Kommandos zur Cover-Generierung in das "opus4" Konsolentool

- application/configs/covers/demo-cover.md
> Demo-Deckblattvorlage nutzt Repository-Metadaten `name` und `url`

- public/layouts/opus4/css/components/publish.css
- public/layouts/opus4/css/theme/theme.css
Optische Trennung von mehreren AutorInnen, GutachterInnen, BetreuerInnen... beim Veröffentlichen
> Update publish.css and theme.css

- RELEASE_NOTES.md
Added extended csv export. Please check if link is correct!
> #1059 Update RELEASE_NOTES.md

- application/configs/application.ini
- modules/frontdoor/controllers/DeliverController.php
> Make use of PDF cover generator optional

- public/layouts/opus4/css/base/base.css
if logged in, this icon will be shown for login-bar element account
> Update base.css with icon for account

- .github/workflows/php.yml
- tests/bin/install_solr_docker.sh
> Dependency caching for Solr in GitHub workflow

- Vagrantfile
> Re-enables the Solr admin UI with Solr 9.x
